In [26]:
#Fields
#PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked

import nltk
import csv
import pandas as pd

In [8]:
##read csv
file_object = csv.reader("train.csv")
for line in file_object:
    print line

['t']
['r']
['a']
['i']
['n']
['.']
['c']
['s']
['v']


In [27]:
##try pandas
train_df = pd.read_csv("train.csv")

In [15]:
for line in train_df:
    print line
    

PassengerId
Survived
Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Cabin
Embarked


In [16]:
train_df.columns

Index([u'PassengerId', u'Survived', u'Pclass', u'Name', u'Sex', u'Age', u'SibSp', u'Parch', u'Ticket', u'Fare', u'Cabin', u'Embarked'], dtype='object')

In [27]:
ageVsSurvival = {}
for index, row in train_df.iterrows():
    print row['Sex'], row['Age'],row['Survived']
    #ageVsSurvival[row['Age']] = ageVsSurvival[row['Age']] + row['Survived']
    

male 22.0 0
female 38.0 1
female 26.0 1
female 35.0 1
male 35.0 0
male nan 0
male 54.0 0
male 2.0 0
female 27.0 1
female 14.0 1
female 4.0 1
female 58.0 1
male 20.0 0
male 39.0 0
female 14.0 0
female 55.0 1
male 2.0 0
male nan 1
female 31.0 0
female nan 1
male 35.0 0
male 34.0 1
female 15.0 1
male 28.0 1
female 8.0 0
female 38.0 1
male nan 0
male 19.0 0
female nan 1
male nan 0
male 40.0 0
female nan 1
female nan 1
male 66.0 0
male 28.0 0
male 42.0 0
male nan 1
male 21.0 0
female 18.0 0
female 14.0 1
female 40.0 0
female 27.0 0
male nan 0
female 3.0 1
female 19.0 1
male nan 0
male nan 0
female nan 1
male nan 0
female 18.0 0
male 7.0 0
male 21.0 0
female 49.0 1
female 29.0 1
male 65.0 0
male nan 1
female 21.0 1
male 28.5 0
female 5.0 1
male 11.0 0
male 22.0 0
female 38.0 1
male 45.0 0
male 4.0 0
male nan 0
male nan 1
female 29.0 1
male 19.0 0
female 17.0 1
male 26.0 0
male 32.0 0
female 16.0 0
male 21.0 0
male 26.0 0
male 32.0 1
male 25.0 0
male nan 0
male nan 0
male 0.83 1
female 30.0 1

In [32]:
len(train_df)

891

In [34]:
classifier = nltk.NaiveBayesClassifier.train(train_df[:500])

ValueError: too many values to unpack

In [8]:
survival = 0 
nonSurvival = 0
for index, row in train_df.iterrows():
    if row['Survived'] == 1:
        survival += 1
    if row['Survived'] == 0:
        nonSurvival += 1
    
print "Survived People",survival,"and Non survived",nonSurvival

Survived People 342 and Non survived 549


In [5]:
import numpy as np
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X,y)
print(clf.predict(X[2]))

[3]


In [8]:
print X,y

[[2 1 4 1 2 4 1 3 3 3 2 3 0 0 0 2 1 4 0 4 3 0 0 1 4 3 4 3 0 3 0 2 2 1 0 3 2
  4 4 0 1 3 4 0 4 3 2 3 4 3 0 0 0 1 1 1 0 3 3 3 0 2 1 3 1 1 0 0 0 2 2 0 3 1
  2 3 0 0 1 2 3 1 4 3 2 2 0 1 3 0 0 4 1 1 1 4 1 2 2 4]
 [2 0 0 1 4 3 1 1 1 2 0 4 0 0 0 4 3 1 0 4 1 1 3 1 3 0 3 1 0 4 2 2 3 4 3 3 0
  3 3 4 1 3 4 3 3 2 1 4 1 1 4 0 3 0 3 2 0 3 1 2 3 2 0 1 1 3 4 3 0 0 2 0 1 0
  0 0 3 2 4 0 0 1 3 4 1 1 1 3 0 4 3 4 2 2 3 0 4 0 1 1]
 [1 1 2 3 0 3 3 3 4 1 1 1 4 4 0 0 2 0 3 3 1 2 1 1 2 0 2 3 0 1 3 1 0 0 0 2 2
  4 4 2 1 1 2 1 3 2 4 0 3 2 1 1 0 3 1 4 0 0 0 4 3 1 4 4 4 4 2 3 4 4 3 4 1 4
  2 3 1 3 2 4 1 4 3 1 1 0 1 1 1 4 1 2 0 2 3 2 2 3 3 4]
 [3 1 3 2 4 2 0 4 3 3 4 2 1 3 0 0 0 1 1 1 0 0 4 3 0 4 3 4 1 3 3 4 2 1 1 1 3
  1 0 2 4 4 4 3 3 1 4 3 3 1 1 2 3 4 1 4 3 2 0 0 4 3 0 3 0 2 4 0 0 0 0 1 1 0
  4 4 4 2 3 2 3 2 4 1 4 1 2 3 3 2 3 3 2 1 0 1 4 1 1 3]
 [3 1 1 4 2 4 2 2 3 0 0 1 4 1 2 0 1 2 2 0 1 1 2 0 1 4 2 0 1 1 0 3 0 1 2 1 3
  3 4 1 1 4 1 3 1 1 2 1 4 1 3 0 4 0 0 0 4 2 3 0 1 0 2 2 2 0 3 2 2 2 4 4 4 2
  3 1 0 4 3 2 4 3 3 

In [24]:
clf.predict(FirstRow[0])

array([2])

In [23]:
FirstRow = np.random.randint(5,size=(1,100))
FirstRow

array([[0, 2, 4, 3, 0, 3, 1, 2, 0, 2, 3, 3, 1, 0, 4, 0, 1, 0, 2, 4, 4, 4,
        3, 3, 3, 1, 4, 1, 0, 4, 4, 3, 3, 1, 3, 1, 4, 2, 4, 2, 2, 2, 3, 4,
        0, 3, 4, 4, 0, 3, 3, 3, 3, 1, 2, 0, 1, 4, 3, 1, 4, 2, 0, 1, 3, 4,
        3, 4, 0, 0, 0, 0, 0, 3, 0, 0, 4, 2, 4, 4, 2, 0, 4, 4, 3, 2, 0, 2,
        0, 1, 3, 2, 4, 3, 4, 1, 0, 0, 3, 3]])

In [56]:
observation = []
survivals = []
for index, row in train_df.iterrows():
    survivals.append(row['Survived'])
    if row['Sex'] == "male":
        observation.append([row['Pclass'], 1, row['Age'] ])
    elif row['Sex'] == "female":
        observation.append([row['Pclass'], 0, row['Age'] ])

np_observation = np.array(observation)
np_survivals = np.array(survivals)

In [57]:
#Both must have equal length for applying the fit model
np_observation


array([[  3.,   1.,  22.],
       [  1.,   0.,  38.],
       [  3.,   0.,  26.],
       ..., 
       [  3.,   0.,  nan],
       [  1.,   1.,  26.],
       [  3.,   1.,  32.]])

In [40]:
titanic_clf = MultinomialNB()
titanic_clf.fit(np_observation,np_survivals)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

NameError: name 'nan' is not defined

In [60]:
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp = imp.fit(np_observation)

# Impute our data, then train
np_observation_imp = imp.transform(np_observation)

In [61]:
np_observation_imp

array([[  3.        ,   1.        ,  22.        ],
       [  1.        ,   0.        ,  38.        ],
       [  3.        ,   0.        ,  26.        ],
       ..., 
       [  3.        ,   0.        ,  29.69911765],
       [  1.        ,   1.        ,  26.        ],
       [  3.        ,   1.        ,  32.        ]])

In [62]:
##using the mean of the age values
titanic_clf_imp = MultinomialNB()
titanic_clf_imp.fit(np_observation_imp,np_survivals)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [64]:
test_df = pd.read_csv("test.csv")
test_df

PassengerId  Pclass                                               Name  \
0            892       3                                   Kelly, Mr. James   
1            893       3                   Wilkes, Mrs. James (Ellen Needs)   
2            894       2                          Myles, Mr. Thomas Francis   
3            895       3                                   Wirz, Mr. Albert   
4            896       3       Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                         Svensson, Mr. Johan Cervin   
6            898       3                               Connolly, Miss. Kate   
7            899       2                       Caldwell, Mr. Albert Francis   
8            900       3          Abrahim, Mrs. Joseph (Sophie Halaut Easu)   
9            901       3                            Davies, Mr. John Samuel   
10           902       3                                   Ilieff, Mr. Ylio   
11           903       1                         Jones, Mr. Charles Cresson   
12           904       1      Snyder, Mrs. John Pillsbury (Nelle Stevenson)   
13           905       2                               Howard, Mr. Benjamin   
14           906       1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...   
15           907       2      del Carlo, Mrs. Sebastiano (Argenia Genovesi)   
16           908       2                                  Keane, Mr. Daniel   
17           909       3                                  Assaf, Mr. Gerios   
18           910       3                       Ilmakangas, Miss. Ida Livija   
19           911       3              Assaf Khalil, Mrs. Mariana (Miriam")"   
20           912       1                             Rothschild, Mr. Martin   
21           913       3                          Olsen, Master. Artur Karl   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
23           915       1                    Williams, Mr. Richard Norris II   
24           916       1    Ryerson, Mrs. Arthur Larned (Emily Maria Borie)   
25           917       3                            Robins, Mr. Alexander A   
26           918       1                       Ostby, Miss. Helene Ragnhild   
27           919       3                                  Daher, Mr. Shedid   
28           920       1                            Brady, Mr. John Bertram   
29           921       3                                  Samaan, Mr. Elias   
..           ...     ...                                                ...   
388         1280       3                               Canavan, Mr. Patrick   
389         1281       3                        Palsson, Master. Paul Folke   
390         1282       1                         Payne, Mr. Vivian Ponsonby   
391         1283       1     Lines, Mrs. Ernest H (Elizabeth Lindsey James)   
392         1284       3                      Abbott, Master. Eugene Joseph   
393         1285       2                               Gilbert, Mr. William   
394         1286       3                           Kink-Heilmann, Mr. Anton   
395         1287       1     Smith, Mrs. Lucien Philip (Mary Eloise Hughes)   
396         1288       3                               Colbert, Mr. Patrick   
397         1289       1  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...   
398         1290       3                     Larsson-Rondberg, Mr. Edvard A   
399         1291       3                           Conlon, Mr. Thomas Henry   
400         1292       1                            Bonnell, Miss. Caroline   
401         1293       2                                    Gale, Mr. Harry   
402         1294       1                     Gibson, Miss. Dorothy Winifred   
403         1295       1                             Carrau, Mr. Jose Pedro   
404         1296       1                       Frauenthal, Mr. Isaac Gerald   
405         1297       2       Nourney, Mr. Alfred (Baron von Drachstedt")"   
406         1298       2                          Ware,

In [65]:
test_data = []
for index, row in test_df.iterrows():
    
    if row['Sex'] == "male":
        test_data.append([row['Pclass'], 1, row['Age'] ])
    elif row['Sex'] == "female":
        test_data.append([row['Pclass'], 0, row['Age'] ])

np_test= np.array(test_data)


In [72]:
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp = imp.fit(np_test)

# Impute our data, then train
np_test_imp = imp.transform(np_test)
submission = titanic_clf_imp.predict(np_test_imp)

In [87]:
test_df_survived =test_df
test_df_survived['Survived'] = submission

In [104]:
# del test_df_survived["Sex"]
# del test_df_survived["Age"]
# del test_df_survived["SibSp"]
# del test_df_survived["Parch"]
# del test_df_survived["Ticket"]
# del test_df_survived["Fare"]
# del test_df_survived["Cabin"]
# del test_df_survived["Embarked"]
# del test_df_survived["Pclass"]
del test_df_survived["Name"]




In [106]:
test_df_survived.to_csv("submission.csv",sep=",", index=False)

In [105]:
test_df_survived

PassengerId  Survived
0            892         0
1            893         1
2            894         1
3            895         0
4            896         0
5            897         0
6            898         0
7            899         0
8            900         0
9            901         0
10           902         0
11           903         0
12           904         1
13           905         1
14           906         1
15           907         0
16           908         0
17           909         0
18           910         0
19           911         1
20           912         1
21           913         0
22           914         1
23           915         0
24           916         1
25           917         0
26           918         0
27           919         0
28           920         0
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         0
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         0
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         0
403         1295         0
404         1296         0
405         1297         0
406         1298         0
407         1299         0
408         1300         0
409         1301         0
410         1302         0
411         1303         1
412         1304         0
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]